### ISSUE TITLE
Exit Full screen  keeps map view expanded 

### ISSUE THREAD

**Issue by xtarx** [quentin-ol/angular2-openlayers#70]
Hello. I am using this code, full screen works but when you exit full screen the map div expands and take more space than it used to be before full screen

```
 <aol-map>
      <aol-view [zoom]="5">
        <aol-coordinate [x]="11.64772" [y]="48.08834" [srid]="'EPSG:4326'"></aol-coordinate>
      </aol-view>
      <aol-interaction-pinchzoom></aol-interaction-pinchzoom><aol-control-zoom></aol-control-zoom>
      <aol-control-fullscreen></aol-control-fullscreen>

      <aol-layer-tile>
        <aol-source-osm></aol-source-osm>
      </aol-layer-tile>
    </aol-map>
```

**Comment by quentin-ol** [comment]
@xtarx 
The ```aol-map```template is: 
```
<div [style.width]="width" [style.height]="height"></div>
```

```width```and ```height``` default to ```100%```.

Therefore, the expected behaviour is that the map fills the parent container if not in fullscreen.
Isn't it what you get?

BTW, it's very difficult to help you on this if you don't provide a minimal example and/or CSS computed styles and screenshots. Indeed, such behaviours may results from inherited CSS rules, interfering JS code that changes elements styles, and, yes, most probably a bug in this library.

**Comment by xtarx** [comment]
yea, I solved it  by over-riding the div CSS

The problem is as you mentioned the div by default takes 100% of width & height

Steps to fix:

1. restrict height to a fixed pixels for example `250px`
2. Add a class for the` <aol-map>` in my case I called it `map`
3. over-ride the class height when in Full-screen mode

* make sure that you added the ol.css from the openlayers library, otherwise the full-screen icon  would be missing or wrongly positioned.


**HTML**

   ```html
 <aol-map class="map map-disable-drag" [width]="'100%'" [height]="'250px'">
      <aol-interaction-default ></aol-interaction-default>
      <aol-interaction-pinchzoom></aol-interaction-pinchzoom>
      <aol-control-fullscreen></aol-control-fullscreen>

      <aol-view [zoom]="19">
        <aol-coordinate [x]="10.65773" [y]="44.08912" [srid]="'EPSG:4326'"></aol-coordinate>
      </aol-view>

      <aol-layer-tile>
        <aol-source-osm></aol-source-osm>
      </aol-layer-tile>
    </aol-map>
```


**CSS**
```css

.map div:first-child:-moz-full-screen {
  pointer-events: all !important;
  height: 100% !important;
}

.map div:first-child:-webkit-full-screen {
  pointer-events: all !important;
  height: 100% !important;
}
.map div:first-child:-ms-fullscreen {
  pointer-events: all !important;
  height: 100% !important;
}
.map div:first-child:fullscreen {
  pointer-events: all !important;
  height: 100% !important;
}
.ol-rotate {
  top: 3em;
}

.ol-full-screen-false{
  pointer-events: all;
}
.map-disable-drag{
  pointer-events:none;

}
```
